# Form implementation generated from reading ui file 'UI/addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(400, 300)
        self.formLayoutWidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 381, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.labelName = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelName.setObjectName("labelName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelName)
        self.nameEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.nameEdit.setObjectName("nameEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.nameEdit)
        self.labelRoastLevel = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelRoastLevel.setObjectName("labelRoastLevel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelRoastLevel)
        self.roastLevelEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.roastLevelEdit.setObjectName("roastLevelEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.roastLevelEdit)
        self.labelGroundOrBeans = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelGroundOrBeans.setObjectName("labelGroundOrBeans")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelGroundOrBeans)
        self.groundOrBeansCombo = QtWidgets.QComboBox(parent=self.formLayoutWidget)
        self.groundOrBeansCombo.setObjectName("groundOrBeansCombo")
        self.groundOrBeansCombo.addItem("")
        self.groundOrBeansCombo.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.groundOrBeansCombo)
        self.labelTasteDescription = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelTasteDescription.setObjectName("labelTasteDescription")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelTasteDescription)
        self.tasteDescriptionEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.tasteDescriptionEdit.setObjectName("tasteDescriptionEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tasteDescriptionEdit)
        self.labelPrice = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelPrice.setObjectName("labelPrice")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPrice)
        self.priceEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.priceEdit.setObjectName("priceEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.priceEdit)
        self.labelPackageVolume = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.labelPackageVolume.setObjectName("labelPackageVolume")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.labelPackageVolume)
        self.packageVolumeEdit = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.packageVolumeEdit.setObjectName("packageVolumeEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.packageVolumeEdit)
        self.saveButton = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.cancelButton.setObjectName("cancelButton")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cancelButton)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Add/Edit Coffee"))
        self.labelName.setText(_translate("AddEditCoffeeForm", "Name:"))
        self.labelRoastLevel.setText(_translate("AddEditCoffeeForm", "Roast Level:"))
        self.labelGroundOrBeans.setText(_translate("AddEditCoffeeForm", "Ground/Beans:"))
        self.groundOrBeansCombo.setItemText(0, _translate("AddEditCoffeeForm", "Ground"))
        self.groundOrBeansCombo.setItemText(1, _translate("AddEditCoffeeForm", "Beans"))
        self.labelTasteDescription.setText(_translate("AddEditCoffeeForm", "Taste Description:"))
        self.labelPrice.setText(_translate("AddEditCoffeeForm", "Price:"))
        self.labelPackageVolume.setText(_translate("AddEditCoffeeForm", "Package Volume:"))
        self.saveButton.setText(_translate("AddEditCoffeeForm", "Save"))
        self.cancelButton.setText(_translate("AddEditCoffeeForm", "Cancel"))
